In [31]:
import glob
import os 
import numpy as np
import cv2
import mediapipe
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import keras 
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Dense,Flatten
from keras.utils import np_utils

# getting all the images from train and test folders

In [32]:
label_list = [chr(i) for i in range(65,90)]
label_list.remove('J')
train_data = []
train_labels = []
test_data = []
test_labels = []
for i in label_list:
    hand_sign_images = glob.glob(r'/Users/vamsi/Downloads/archive/Train/'+str(i)+'/*.*')
    for j in hand_sign_images:
        img=cv2.imread(j)
        
        train_data.append(img)
        train_labels.append(i)
for i in label_list:
    hand_sign_images = glob.glob(r'/Users/vamsi/Downloads/archive/Test/'+str(i)+'/*.*')
    for j in hand_sign_images:
        img=cv2.imread(j)
        test_data.append(img)
        test_labels.append(i)  


In [37]:
test_data[3].shape

(28, 28, 3)

In [3]:
train_data = np.array(train_data)
train_labels = np.array(train_labels)
test_data = np.array(test_data)
test_labels = np.array(test_labels)

In [4]:
train_data.shape

(27455, 28, 28, 3)

In [5]:
train_labels.shape

(27455,)

In [6]:
test_data.shape

(7172, 28, 28, 3)

In [7]:
test_labels.shape

(7172,)

In [8]:
train_data = train_data/255
test_data = test_data/255

In [1]:
#train_labels = np_utils.to_categorical(train_labels,24,)
#test_labels= np_utils.to_categorical(test_labels,24)

In [10]:
train_label = pd.DataFrame(train_labels)
test_label = pd.DataFrame(test_labels)

In [11]:
train_label

0
0      A
1      A
2      A
3      A
4      A
...   ..
27450  Y
27451  Y
27452  Y
27453  Y
27454  Y

[27455 rows x 1 columns]

In [12]:
test_label

0
0     A
1     A
2     A
3     A
4     A
...  ..
7167  Y
7168  Y
7169  Y
7170  Y
7171  Y

[7172 rows x 1 columns]

In [13]:
for i in train_label.columns:
    if train_label[i].dtype=='object':
        encoded = pd.get_dummies(train_label[i])
        train_label = train_label.join(encoded).drop(i, axis=1)
for i in test_label.columns:
    if test_label[i].dtype=='object':
        encoded = pd.get_dummies(test_label[i])
        test_label = test_label.join(encoded).drop(i, axis=1)

In [14]:
train_label

A  B  C  D  E  F  G  H  I  K  ...  P  Q  R  S  T  U  V  W  X  Y
0      1  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
1      1  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
2      1  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
3      1  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
4      1  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
...   .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
27450  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  1
27451  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  1
27452  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  1
27453  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  1
27454  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  1

[27455 rows x 24 columns]

In [15]:
test_label

A  B  C  D  E  F  G  H  I  K  ...  P  Q  R  S  T  U  V  W  X  Y
0     1  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
1     1  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
2     1  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
3     1  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
4     1  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
7167  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  1
7168  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  1
7169  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  1
7170  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  1
7171  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  1

[7172 rows x 24 columns]

In [16]:
train_label = np.array(train_label,dtype='float32')
test_label = np.array(test_label,dtype='float32')

In [17]:
train_label

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [18]:
test_label

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [19]:
train_label.shape

(27455, 24)

In [20]:
test_label.shape

(7172, 24)

In [21]:
model = Sequential()
model.add(Conv2D(20,(5,5),padding='valid',activation='relu',input_shape=(28,28,3))) #convolutional layer
model.add(MaxPooling2D(pool_size=(2,2))) #pooling layer 
model.add(Conv2D(10,(5,5),padding='valid',activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten()) #convert image to a vector 

model.add(Dense(120,activation='relu')) # 120 neruons 
model.add(Dense(24,activation='softmax')) # output layer

2023-04-18 10:43:42.222516: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 20)        1520      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 12, 12, 20)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 8, 8, 10)          5010      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 4, 4, 10)         0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 160)               0         
                                                                 
 dense (Dense)               (None, 120)               1

In [29]:
train_data

array([[[[0.24313725, 0.24313725, 0.24313725],
         [0.38431373, 0.38431373, 0.38431373],
         [0.38823529, 0.38823529, 0.38823529],
         ...,
         [0.56470588, 0.56470588, 0.56470588],
         [0.56862745, 0.56862745, 0.56862745],
         [0.57254902, 0.57254902, 0.57254902]],

        [[0.25490196, 0.25490196, 0.25490196],
         [0.38431373, 0.38431373, 0.38431373],
         [0.37254902, 0.37254902, 0.37254902],
         ...,
         [0.56470588, 0.56470588, 0.56470588],
         [0.57254902, 0.57254902, 0.57254902],
         [0.57647059, 0.57647059, 0.57647059]],

        [[0.31764706, 0.31764706, 0.31764706],
         [0.40784314, 0.40784314, 0.40784314],
         [0.34117647, 0.34117647, 0.34117647],
         ...,
         [0.57254902, 0.57254902, 0.57254902],
         [0.57647059, 0.57647059, 0.57647059],
         [0.58039216, 0.58039216, 0.58039216]],

        ...,

        [[0.17647059, 0.17647059, 0.17647059],
         [0.0745098 , 0.0745098 , 0.0745098 ]

In [23]:
model.compile(optimizer="Adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [24]:
model.fit(train_data,train_label,batch_size=10,epochs=100,verbose=1,validation_split=0.2)

Epoch 1/100
2197/2197 [==============================] - 12s 5ms/step - loss: 0.7456 - accuracy: 0.7639 - val_loss: 19.5388 - val_accuracy: 0.0907
Epoch 2/100
2197/2197 [==============================] - 10s 5ms/step - loss: 0.0745 - accuracy: 0.9775 - val_loss: 26.6945 - val_accuracy: 0.1364
Epoch 3/100
2197/2197 [==============================] - 10s 5ms/step - loss: 0.0415 - accuracy: 0.9883 - val_loss: 24.3785 - val_accuracy: 0.1044
Epoch 4/100
2197/2197 [==============================] - 10s 5ms/step - loss: 0.0290 - accuracy: 0.9917 - val_loss: 26.7262 - val_accuracy: 0.1635
Epoch 5/100
2197/2197 [==============================] - 10s 5ms/step - loss: 0.0011 - accuracy: 0.9999 - val_loss: 32.9987 - val_accuracy: 0.1643
Epoch 6/100
2197/2197 [==============================] - 10s 5ms/step - loss: 1.5668e-04 - accuracy: 1.0000 - val_loss: 36.6896 - val_accuracy: 0.1643
Epoch 7/100
2197/2197 [==============================] - 10s 5ms/step - loss: 0.0325 - accuracy: 0.9902 - val_loss

In [26]:
model.evaluate(test_data,test_label)

225/225 [==============================] - 1s 4ms/step - loss: 10.4905 - accuracy: 0.7482


[10.490517616271973, 0.7481874227523804]

In [33]:
label = 'HI'
labels={0:'A',1:'B',2:'C',3:'D',4:'E',5:'F',6:'G',7:'H',8:'I',9:'k',10:'L',11:'M',12:'N',13:'O',14:'P',15:'Q',16:'R',17:'S',18:'T',19:'U',20:'V',21:'W',22:'X',23:'Y'}
drawingModule = mediapipe.solutions.drawing_utils
handsModule = mediapipe.solutions.hands
capture = cv2.VideoCapture(0)
x=[]
y=[]
with handsModule.Hands(static_image_mode=False, min_detection_confidence=0.7, min_tracking_confidence=0.7,max_num_hands=2) as hands:
        z=0
        while (True):
            ret, frame = capture.read()
            results = hands.process(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
            if results.multi_hand_landmarks:
                for handLandmarks in results.multi_hand_landmarks:
                    drawingModule.draw_landmarks(frame, handLandmarks, handsModule.HAND_CONNECTIONS)
                    for i in range(0,21):
                        x.append(results.multi_hand_landmarks[0].landmark[i].x)
                        y.append(results.multi_hand_landmarks[0].landmark[i].y)
                    x1=min(x)
                    x2=max(x)
                    y1=min(y)
                    y2=max(y)
                    x.clear()
                    y.clear()
                    h, w, c = frame.shape
                    x11= int(x1 *w)
                    y11 = int(y1*h)
                    x21 = int(x2 *w)
                    y21 = int(y2*h)
                    cv2.rectangle(frame,(x11-30,y11-30),(x21+30,y21+30),(255,0,255),1)
                    image1 = frame[y11-30:y21+30,x11-30:x21+30]
                    if cv2.waitKey(1) == ord('t'):
                        #cv2.imwrite(r"/Volumes/study/face_mask_data_kaggel/{}.jpg".format(z),image1)
                        #z=z+1
                        image1 = image1/255
                        image2 = cv2.resize(image1,(28,28))
                        image21 = image2.reshape(1,image2.shape[0],image2.shape[1],image2.shape[2])
                        #cv2.imwrite(r"/Volumes/study/face_mask_data_kaggel/0.jpg",image2)
                        pre = model.predict(image21)
                        label = labels[np.argmax(pre)]
                        print("the label is",label)
            cv2.putText(frame,label,(100,100),cv2.FONT_HERSHEY_SIMPLEX,1, (209, 80, 0, 255),3) 
            cv2.imshow('Test hand', frame)
            if cv2.waitKey(1) == ord('q'):
                break
cv2.destroyAllWindows()
capture.release()

1/1 [==============================] - 0s 84ms/step
the label is P
1/1 [==============================] - 0s 18ms/step
the label is C
1/1 [==============================] - 0s 18ms/step
the label is S
1/1 [==============================] - 0s 18ms/step
the label is P
1/1 [==============================] - 0s 18ms/step
the label is A
1/1 [==============================] - 0s 18ms/step
the label is T
1/1 [==============================] - 0s 18ms/step
the label is L
1/1 [==============================] - 0s 18ms/step
the label is A
1/1 [==============================] - 0s 18ms/step
the label is A
1/1 [==============================] - 0s 18ms/step
the label is N
1/1 [==============================] - 0s 18ms/step
the label is E
1/1 [==============================] - 0s 18ms/step
the label is O
1/1 [==============================] - 0s 18ms/step
the label is C
1/1 [==============================] - 0s 18ms/step
the label is T
1/1 [==============================] - 0s 18ms/step
the label 